config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
	</tr>

	<% @articles.each do |article| %>
		<tr>
			<td><%= article.title %></td>
			<td><%= article.text %></td>
			<td><%= link_to 'show', article_path(article) %></td>
		</tr>
	<%end%>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %> <br>
		<%= f.text_field :title %> <br>
	</p>
	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %><br>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>